# To see what comes out after this template is processed, run:
#    conda-render ./conda/

{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: "{{ data.version }}"

source:
  # Source from tarball
  # note: must 'make dist-pypi' or `python setup.py sdist` before running conda-build as we now rely on MANIFEST.IN to
  # only pick desired files and avoid copying data folders and alike - and its puts its clean tarball under /dist/:
  url: ../dist/{{ data.name }}-{{ data.version }}.tar.gz

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

# PyQt5 and ase are not available on conda so they are installed via the script above
requirements:
  build:
    - conda-build
  host:
    - python =3.8
    - pip
  run:
    - python =3.8

    - astropy
    - xarray >=0.16.1
    - h5py >=3.2.1
    - pyqtgraph >=0.12.0,<0.13.0
    - pyqt

    - pint
    - pandas
    - numpy>=1.20.0,<2.0.0
    - scipy>=1.6.0,<2.0.0
    - netcdf4 >=1.5.0,<2.0.0
    - lmfit >=1.0.0,<2.0.0

    - colorcet
    - matplotlib >=3.0.3
    - bokeh>=2.0.0
    - ipywidgets >=7.0.1,<8.0.0

    - scikit-learn >=0.24.0,<1.0.0

    - packaging
    - numba >=0.53.0,<1.0.0

    - colorama
    - imageio
    - titlecase

    - tqdm
    - rx
    - dill


test:
  imports:
    - arpes
  requires:
    - python

about:
  home: https://arpes.readthedocs.io/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Modular data analysis code for angle resolved photoemission spectroscopy (ARPES)'
  description: 'Modular data analysis code for angle resolved photoemission spectroscopy (ARPES)'
  doc_url: https://arpes.readthedocs.io/
  dev_url: https://gitlab.com/lanzara-group/python-arpes

extra:
  recipe-maintainers:
    - chstan
  deploy:
    - anaconda-client
    - setuptools >=0.39
    - twine >=1.12
